Repository swaponline/MultiCurrencyWallet, pull requests merged in 2018-12, with the labels that each got.

#1064 extra char in the downloaded private key file
  shared/redux/actions/user.js
Labels: buidl

#1063 fix indent
  shared/components/PageHeadline/PageHeadline.scss
  shared/pages/Wallet/Wallet.scss
Labels: buidl

#1069 #1018: show reputation
  config/mainnet/api.js
  config/testnet/api.js
  shared/components/Avatar/Avatar.js
  shared/components/Header/User/User.js
  shared/components/Header/User/User.scss
  shared/containers/App/App.js
  shared/redux/actions/btc.js
  shared/redux/actions/eth.js
  shared/redux/actions/user.js
  shared/redux/reducers/ipfs.js
  shared/redux/reducers/user.js
Labels: buidl

#1088 package.json: run npm audit fix - automatically fix vulnerabilities
  package.json
Labels: buidl

#1085 exchange: Alternative destination address unclear
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/SelectGroup/SelectGroup.js
Labels: buidl

#1098 partial: cryptonator fix many requests flood
  shared/helpers/request.js
  shared/pages/PartialClosure/PartialClosure.js
Labels: buidl

#1073 #587 - add swap progress : btc/eth, eth/btc
  shared/components/SwapProgress/SwapProgress.js
  shared/components/SwapProgress/SwapProgress.scss
  shared/components/loaders/RequestLoader/RequestLoader.js
  shared/pages/PartialClosure/PartialClosure.scss
  shared/pages/Swap/BtcToEth.js
  shared/pages/Swap/EthToBtc.js
  shared/pages/Swap/Swap.js
  shared/pages/Swap/Swap.scss
  shared/redux/actions/loader.js
Labels: buidl

#1120 Fix for browsers unsupported service worker
  shared/components/Header/Header.js
  shared/components/Header/User/AddOfferButton/AddOfferButton.js
  shared/components/Header/User/SubscribeButton/SubscribeButton.js
  shared/components/Header/User/SubscribeButton/SubscribeButton.scss
  shared/components/Header/User/SubscribeButton/images/add.svg
  shared/components/Header/User/User.js
  shared/containers/App/App.js
  shared/redux/actions/pushNotification/index.js
Labels: buidl

#1129 Add user data with a positive balance to the Firebase data base
  shared/components/Header/User/SubscribeButton/SubscribeButton.js
  shared/components/modals/PrivateKeysModal/PrivateKeysModal.js
  shared/components/modals/SubscribeModal/SubscribeModal.js
  shared/containers/App/App.js
  shared/redux/actions/firebase/config/firebase.js
  shared/redux/actions/firebase/index.js
  shared/redux/actions/index.js
  shared/redux/actions/pushNotification/index.js
Labels: buidl

#1149 Add LTC to import keys form
  shared/components/modals/ImportKeys/ImportKeys.js
Labels: buidl

#1146 Fix updating exchange rate when changing swap direction
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
Labels: buidl

#1110 запрет на создание не существ. валютных пар
  shared/components/CurrencyDirectionChooser/CurrencyDirectionChooser.js
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/components/ui/CurrencyIcon/CurrencyIcon.js
  shared/components/ui/CurrencySelect/CurrencySelect.js
  shared/components/ui/CurrencySelect/Option/Option.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/Home/Home.js
  shared/pages/Home/Orders/Orders.js
  shared/pages/PartialClosure/PartialClosure.js
  shared/redux/actions/index.js
  shared/redux/actions/pairs.js
  shared/redux/reducers/currencies.js
Labels: need review

#1182 При открытии модалки addOffer exchange rate равен 1, а должен обновиться
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
Labels: buidl, need review

#1211 modal: fix title position
  shared/components/modal/Modal/Modal.scss
Labels: buidl, need review

#1209 header: add UserTooltip for mobile version
  shared/components/Header/Header.js
  shared/containers/App/App.js
Labels: buidl, need review

#1196 subscribe: add modal at start page, disable button after subscribing …
  package.json
  shared/components/Header/Header.js
  shared/components/Header/User/SignUpButton/SignUpButton.js
  shared/components/Header/User/SignUpButton/SignUpButton.scss
  shared/components/Header/User/SignUpButton/images/add.svg
  shared/components/Header/User/User.js
  shared/components/modals/SignUpModal/SignUpModal.js
  shared/components/modals/SignUpModal/SignUpModal.scss
  shared/components/modals/SubscribeModal/SubscribeModal.js
  shared/components/modals/index.js
  shared/helpers/constants/localStorage.js
  shared/helpers/constants/modals.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/redux/actions/firebase/index.js
  shared/redux/middleware/index.js
  shared/redux/middleware/saver.js
  shared/redux/reducers/index.js
  shared/redux/reducers/signUp.js
  shared/redux/store/index.js
Labels: buidl, need review

#1178 Команда для создания билда только с одним токеном, отсуствующем в конфиге, без футера и шапки (для вставки в сайт)
  config/mainnet.widget.dev.js
  config/testnet.widget.dev.js
  config/testnet.widget.prod.js
  package.json
  shared/components/Footer/Footer.js
  shared/components/Header/Header.js
  shared/containers/App/App.js
  shared/pages/PartialClosure/PartialClosure.js
  shared/routes/index.js
Labels: draft

#1231 signUp: add email request, add optimization
  shared/components/modals/PrivateKeysModal/PrivateKeysModal.js
  shared/components/modals/SignUpModal/SignUpModal.js
  shared/components/modals/SignUpModal/SignUpModal.scss
  shared/containers/App/App.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/redux/actions/firebase/index.js
Labels: buidl, in progress

#1238 redux: add signUpSaver, remove saver
  shared/redux/middleware/index.js
  shared/redux/middleware/saver.js
  shared/redux/middleware/signUpSaver.js
  shared/redux/store/index.js
Labels: buidl, need review
