Repository swaponline/MultiCurrencyWallet, pull requests merged in 2018-11, with the labels that each got.

#804 check status of eos account
  shared/redux/actions/eos.js
  shared/redux/actions/user.js
Labels: in progress

#812 Update pull_request_template.md
  .github/pull_request_template.md
  shared/components/Footer/Info/Info.scss
Labels: in progress

#813 add disabled button after submit button
  shared/components/modals/WithdrawModal/WithdrawModal.js
Labels: in progress

#805 #765 - Fix: adaptive exchange page, adaptive your orders
  shared/components/CurrencyDirectionChooser/CurrencyDirectionChooser.js
  shared/components/CurrencyDirectionChooser/CurrencyDirectionChooser.scss
  shared/components/controls/Flip/Flip.scss
  shared/components/controls/RemoveButton/RemoveButton.scss
  shared/components/ui/DropDown/DropDown.js
  shared/components/ui/DropDown/DropDown.scss
  shared/pages/Home/Home.scss
  shared/pages/Home/Orders/MyOrders/MyOrders.js
  shared/pages/Home/Orders/MyOrders/RowFeedsMobile/RowFeedsMobile.js
  shared/pages/Home/Orders/MyOrders/RowFeedsMobile/RowFeedsMobile.scss
  shared/pages/Home/Orders/MyOrders/RowFeedsMobile/images/accept.svg
  shared/pages/Home/Orders/MyOrders/RowFeedsMobile/images/arrow-right.svg
  shared/pages/Home/Orders/MyOrders/RowFeedsMobile/images/share-alt-solid.svg
Labels: in progress

#819 новые условия листинга
  shared/pages/Listing/Listing.js
Labels: in progress

#824 Fix: wallet table thead, aligned cells, paddings
  shared/components/tables/Table/Table.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
Labels: in progress

#829 replase ipfs info
  shared/components/Footer/Info/Info.scss
Labels: in progress

#831 upgradeCode
  shared/pages/Listing/Listing.js
Labels: in progress

#834 Fifx issue #832;
  shared/containers/App/App.js
  shared/redux/actions/analytics.js
Labels: in progress

#835 #799 - Fix: Wallet page ux problem, exchange page ( equal selects on exchange page )
  shared/components/controls/WithdrawButton/WithdrawButton.js
  shared/components/tables/Table/Table.scss
  shared/components/ui/DropDown/DropDown.js
  shared/components/ui/DropDown/DropDown.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
Labels: in progress

#836 Fix: mobile loader, wallet buttons bug
  shared/components/loaders/Loader/Loader.js
  shared/components/loaders/Loader/Loader.scss
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#837 add eos activation button
  shared/pages/CurrencyWallet/CurrencyWallet.js
Labels: in progress

#841 Fix: wallet page bugs
  shared/components/CurrencyDirectionChooser/CurrencyDirectionChooser.scss
  shared/components/tables/Table/Table.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
Labels: in progress

#843 Update extension builder;
  chrome-extension/manifest.json
  package.json
Labels: in progress

#845 fix order values error
  shared/pages/Home/Orders/Pair.js
Labels: in progress

#846 save debug swap to global window.swap
  shared/pages/Swap/Swap.js
Labels: in progress

#847 #828 - Fix wallet page on all devices, all media and mobile
  shared/components/tables/Table/Table.js
  shared/components/tables/Table/Table.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
  shared/pages/Wallet/Wallet.js
  shared/pages/Wallet/Wallet.scss
Labels: in progress

#849 Partial closure
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/OfferModal/ConfirmOffer/ConfirmOffer.js
  shared/components/ui/CurrencySelect/CurrencySelect.js
  shared/containers/Core/Core.js
  shared/helpers/links.js
  shared/pages/Home/Orders/Row/Row.js
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/PartialClosure.scss
  shared/pages/PartialClosure/SelectGroup/SelectGroup.js
  shared/pages/PartialClosure/SelectGroup/SelectGroup.scss
  shared/redux/actions/core.js
  shared/routes/index.js
Labels: in progress

#856 Add token
  config/mainnet/erc20.js
Labels: in progress

#853 Ipfs loading
  shared/containers/Core/Core.js
Labels: in progress

#860 transfer button
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/pages/Currency/Currency.js
  shared/pages/Swap/BtcToEthToken.js
  shared/redux/actions/btc.js
  shared/redux/actions/ltc.js
Labels: in progress

#864 Fix issue #852;
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/pages/Home/Orders/Orders.js
Labels: in progress

#868 fix TNT decimals error
  config/mainnet/erc20.js
Labels: in progress

#866 Discord
  shared/components/Footer/SocialMenu/SocialMenu.js
  shared/helpers/links.js
Labels: in progress

#863 partial closure tooltip
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/ui/Tooltip/Tooltip.js
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#869 one-line deploy script
  .gitignore
  deploy
  package.json
Labels: in progress

#870 remove extra trailing id's
  shared/pages/Listing/Listing.js
Labels: in progress

#876 update
  shared/pages/PartialClosure/PartialClosure.js
Labels: in progress

#877 change have and get currency
  shared/pages/PartialClosure/PartialClosure.js
Labels: in progress

#874 Update issue templates
  .github/ISSUE_TEMPLATE/complex-manual-test.md
Labels: in progress

#887 fix UI
  shared/components/ui/DropDown/DropDown.scss
Labels: in progress

#884 fix #882
  shared/pages/CurrencyWallet/CurrencyWallet.js
Labels: in progress

#888 delete repeat refund on hisotry swap
  shared/pages/History/SwapsHistory/RowHistory/RowHistory.js
Labels: in progress

#889 fix repeat swap history
  shared/pages/Swap/Swap.js
Labels: in progress

#880 add check have, get amount and declined offer
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/PartialClosure.scss
Labels: in progress

#891 добавить видео на странице партиал
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/PartialClosure.scss
Labels: in progress

#893 fix sort order
  shared/pages/PartialClosure/PartialClosure.js
Labels: in progress

#906 indent between : and text
  shared/components/Href/TransactionLink.js
  shared/components/notifications/ErrorNotification/ErrorNotification.js
  shared/pages/CurrencyWallet/CurrencyWallet.js
Labels: in progress

#907 add tokens by cycle
  shared/pages/History/LinkTransaction/LinkTransaction.js
Labels: in progress

#902 Add address and address link for swap, then it's not enough money for…
  shared/pages/Swap/BtcToEth.js
  shared/pages/Swap/BtcToEthToken.js
  shared/pages/Swap/BtcToLtc.js
  shared/pages/Swap/EthToBtc.js
  shared/pages/Swap/EthToLtc.js
  shared/pages/Swap/EthTokenToBtc.js
  shared/pages/Swap/EthTokenToUsdt.js
  shared/pages/Swap/LtcToBtc.js
  shared/pages/Swap/LtcToEth.js
  shared/pages/Swap/Swap.js
  shared/pages/Swap/UsdtToEthToken.js
Labels: in progress

#913 change menu affiliate to About Us, frame https://wiki.swap.online/abo…
  shared/components/Footer/Links/Links.js
  shared/components/Header/Header.js
  shared/helpers/links.js
  shared/helpers/seo.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/About/About.js
  shared/pages/Affiliate/Affiliate.js
  shared/routes/index.js
Labels: in progress

#920 1)Fix: deposit btn, hover on disabled btns - 2) Fix: responsive wallet page
  shared/components/tables/Table/Table.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
  shared/pages/Wallet/Wallet.js
  shared/pages/Wallet/Wallet.scss
Labels: in progress

#925 frame height
  shared/pages/About/About.js
Labels: in progress

#910 duplicate Function to props
  shared/pages/Home/Orders/Orders.js
  shared/pages/Home/Orders/Orders.scss
  shared/pages/Home/Orders/Row/Row.js
  shared/pages/Home/Orders/RowMobile/RowMobile.js
Labels: in progress

#905 Error notification get style from type
  shared/components/notification/Notification/Notification.js
  shared/components/notification/Notification/Notification.scss
  shared/components/notifications/ErrorNotification/ErrorNotification.js
  shared/components/notifications/ErrorNotification/ErrorNotification.scss
  shared/pages/Swap/Swap.js
Labels: in progress

#926 qr modal optimization style, text align and size
  shared/components/modals/ReceiveModal/ReceiveModal.js
Labels: in progress

#927 Revert "set destination address for tokens"
  .gitmodules
  shared/components/ui/CurrencySelect/Option/Option.js
  shared/components/ui/CurrencySelect/Option/Option.scss
  shared/components/ui/DropDown/DropDown.scss
  shared/pages/Swap/BtcToEthToken.js
Labels: in progress

#928 set token destination address (to develop merge)
  .gitmodules
  shared/components/ui/CurrencySelect/Option/Option.js
  shared/components/ui/CurrencySelect/Option/Option.scss
  shared/components/ui/DropDown/DropDown.scss
  shared/pages/Swap/BtcToEthToken.js
Labels: in progress

#931 Revert "Add address and address link for swap, then it's not enough money for…"
  shared/pages/Swap/BtcToEth.js
  shared/pages/Swap/BtcToEthToken.js
  shared/pages/Swap/BtcToLtc.js
  shared/pages/Swap/EthToBtc.js
  shared/pages/Swap/EthToLtc.js
  shared/pages/Swap/EthTokenToBtc.js
  shared/pages/Swap/EthTokenToUsdt.js
  shared/pages/Swap/LtcToBtc.js
  shared/pages/Swap/LtcToEth.js
  shared/pages/Swap/Swap.js
  shared/pages/Swap/UsdtToEthToken.js
Labels: in progress

#934 destination address for tokens
  shared/pages/Swap/BtcToEthToken.js
Labels: in progress

#929 Update issue templates
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/complex-manual-test.md
  .github/ISSUE_TEMPLATE/improvement-template.md
  .github/ISSUE_TEMPLATE/new-blockchain-manual-test.md
  .github/ISSUE_TEMPLATE/standart-task-template.md
Labels: in progress

#935 Update pull_request_template.md
  .github/pull_request_template.md
Labels: in progress

#938 currency icon with title wrap fix + zorder
  shared/components/ui/CurrencySelect/Option/Option.js
  shared/components/ui/CurrencySelect/Option/Option.scss
  shared/components/ui/DropDown/DropDown.scss
Labels: in progress

#939 Add address and address link for swap, then it's not enough money for…
  shared/pages/Swap/BtcToEth.js
  shared/pages/Swap/BtcToEthToken.js
  shared/pages/Swap/BtcToLtc.js
  shared/pages/Swap/EthToBtc.js
  shared/pages/Swap/EthToLtc.js
  shared/pages/Swap/EthTokenToBtc.js
  shared/pages/Swap/EthTokenToUsdt.js
  shared/pages/Swap/LtcToBtc.js
  shared/pages/Swap/LtcToEth.js
  shared/pages/Swap/Swap.js
  shared/pages/Swap/UsdtToEthToken.js
Labels: in progress

#942 upload balance with unconfirmedBalance balance BETA
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#943 Fix: mobile confirm modal
  shared/components/modals/OfferModal/ConfirmOffer/ConfirmOffer.scss
Labels: in progress

#945 Revert "upload balance with unconfirmedBalance balance BETA"
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#947 issue #908 #867
  shared/components/modals/ShowMoreCoins/ShowMoreCoins.js
  shared/pages/PartialClosure/PartialClosure.js
Labels: in progress

#953 fix name telosData on show more coins modal
  shared/components/modals/ShowMoreCoins/ShowMoreCoins.js
Labels: in progress

#960 change command for start lint validation
  .github/pull_request_template.md
Labels: in progress

#949 wallet: unconfirmed balance
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#959 Fix incorrectly disabling TRANSFER button in Withdraw modal
  shared/components/modals/WithdrawModal/WithdrawModal.js
Labels: in progress

#957 tooltip send/exchange/deposit
  shared/components/controls/WithdrawButton/BtnTooltip.js
  shared/components/controls/WithdrawButton/WithdrawButton.js
  shared/components/controls/WithdrawButton/WithdrawButton.scss
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Row/Row.scss
Labels: in progress

#972 travis: linter will check changed commit range
  .travis.yml
  package.json
Labels: in progress

#971 package.json: linter checks changed files before each commit
  package.json
Labels: in progress

#969 wallet: typo in Exchange button text
  shared/pages/Wallet/Row/Row.js
Labels: in progress

#975 Revert "Code contains deprecated componentWillReceiveProps/componentWillMount hook"
  local_modules/sw-valuelink/tags.js
  shared/components/Header/User/UserAvatar/UserAvatar.js
  shared/components/Seo/Seo.js
  shared/components/forms/TextArea/TextArea.js
  shared/components/modal/ModalConductor/ModalConductor.js
  shared/components/modals/SaveKeysModal/SaveKeysModal.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/containers/App/App.js
  shared/containers/Core/Core.js
  shared/pages/Currency/Currency.js
  shared/pages/Home/Home.js
  shared/pages/Home/Orders/MyOrders/RowFeeds/RowFeeds.js
  shared/pages/Home/Orders/Row/Row.js
  shared/pages/Home/Orders/RowMobile/RowMobile.js
  shared/pages/Swap/BtcToEos.js
  shared/pages/Swap/BtcToEth.js
  shared/pages/Swap/BtcToEthToken.js
  shared/pages/Swap/BtcToLtc.js
  shared/pages/Swap/EosToBtc.js
  shared/pages/Swap/EthToBtc.js
  shared/pages/Swap/EthToLtc.js
  shared/pages/Swap/EthTokenToBtc.js
  shared/pages/Swap/EthTokenToUsdt.js
  shared/pages/Swap/LtcToBtc.js
  shared/pages/Swap/LtcToEth.js
  shared/pages/Swap/Swap.js
  shared/pages/Swap/Timer/Timer.js
  shared/pages/Swap/UsdtToEthToken.js
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Wallet.js
Labels: in progress

#984 orders: row mobile said you get you get, fix to match logic
  shared/pages/Home/Orders/Row/Row.js
  test.txt
Labels: in progress

#998 Update chrome extension version to 1.1.0
  chrome-extension/manifest.json
  package.json
Labels: in progress

#1014 switch currency exchange modal
  shared/components/controls/Switching/Switching.js
  shared/components/controls/Switching/Switching.scss
  shared/components/controls/Switching/images/Switching.svg
  shared/components/controls/index.js
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/OfferModal/AddOffer/Select/Select.js
Labels: buidl

#983 Тhere is way to open many pages
  shared/containers/App/App.js
  shared/containers/Core/Core.js
  shared/helpers/constants/localStorage.js
Labels: buidl

#974 Wallet rows rerender too much time
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Wallet.js
Labels: buidl

#999 Partial custom wallet
  shared/components/ui/CurrencySelect/Option/Option.js
  shared/pages/PartialClosure/PartialClosure.js
Labels: buidl, in progress

#1007 fix issues 986
  shared/pages/Swap/BtcToEthToken.js
Labels: buidl

#981 listing in new window
  shared/components/Header/Header.js
  shared/components/Header/Nav/Nav.js
  shared/helpers/links.js
  shared/routes/index.js
Labels: buidl, in progress
