Repository swaponline/MultiCurrencyWallet, pull requests merged in 2019-01, with the labels that each got.

#1246 redux: add selectiveSaver, remove saver, fix clean redux store
  shared/redux/middleware/index.js
  shared/redux/middleware/saver.js
  shared/redux/middleware/selectiveSaver.js
  shared/redux/store/index.js
Labels: buidl, need review

#1252 SignUpButton: change mobile button icon
  shared/components/Header/User/SignUpButton/SignUpButton.js
Labels: buidl

#1255 header: hide header when input is in focus
  shared/components/Header/Header.js
  shared/components/Header/Header.scss
  shared/components/forms/Input/Input.js
  shared/components/ui/DropDown/DropDown.js
  shared/components/ui/DropDown/DropDown.scss
  shared/redux/reducers/index.js
  shared/redux/reducers/inputActive.js
Labels: buidl, need review

#1269 exchange: Альтернативный адрес для направлений btc-eth btc-token eth-btc
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/PartialClosure.scss
Labels: buidl

#1265 redux: add setFee to reducer
  config/mainnet/feeRates.js
  config/mainnet/index.js
  config/testnet/feeRates.js
  config/testnet/index.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/containers/App/App.js
  shared/helpers/btc.js
  shared/helpers/constants/DEFAULT_FEE_RATES.js
  shared/helpers/constants/index.js
  shared/helpers/eth.js
  shared/helpers/ethToken.js
  shared/helpers/index.js
  shared/helpers/ltc.js
  shared/instances/newSwap.js
  shared/redux/actions/btc.js
  shared/redux/actions/eos.js
  shared/redux/actions/eth.js
  shared/redux/actions/ltc.js
  shared/redux/actions/tlos.js
  shared/redux/actions/token.js
  shared/redux/actions/usdt.js
  shared/redux/actions/user.js
  shared/redux/reducers/user.js
Labels: buidl, need review

#1286 newSwap: fix options for core
  shared/instances/newSwap.js
Labels: need review

#1299 newSwap: fix gas limit for core
  shared/instances/newSwap.js
Labels: buidl

#1318 addOffer: fix eth balance
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
Labels: buidl, need review

#1327 history: fix output value, add self type of transaction
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/History/Row/Row.js
  shared/pages/History/Row/Row.scss
  shared/redux/actions/btc.js
Labels: buidl, need review

#1329 wallet: add checkImportKeyHash
  shared/pages/Wallet/Wallet.js
Labels: buidl, need review

#1331 location: fix coins names to uppercase fot ImportKeys modal
  shared/components/modals/ImportKeys/ImportKeys.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
Labels: buidl, need review

#1345 newSwap: add hot fix fetchTxInfo for btcSwap
  shared/instances/newSwap.js
Labels: buidl, need review

#1342 helpers: add key "method" to estimateFeeValue
  shared/containers/App/App.js
  shared/helpers/btc.js
  shared/helpers/constants/DEFAULT_FEE_RATES.js
  shared/helpers/eth.js
  shared/helpers/ethToken.js
  shared/helpers/ltc.js
  shared/redux/actions/btc.js
  shared/redux/actions/eth.js
  shared/redux/actions/ltc.js
  shared/redux/actions/token.js
  shared/redux/actions/user.js
  shared/redux/reducers/user.js
Labels: buidl, need review

#1361 redux: fix actions "send" for actual fee value
  shared/redux/actions/btc.js
  shared/redux/actions/eth.js
  shared/redux/actions/token.js
Labels: buidl, need review

#1365 wallet: temporal disable ltc
  config/mainnet/api.js
  config/mainnet/link.js
  shared/pages/Wallet/Wallet.js
Labels: buidl, need review

#1376 redux: fix gasLimit for send ethToken
  shared/redux/actions/token.js
Labels: need review

#1377 вынести, чтоб прелоадер показывался до того как реакт загрузится, иначе смысла от него нет
  client/index.html
Labels: buidl

#1387 helpers: add BN to estimateGasPrice/FeeRate
  config/testnet/feeRates.js
  shared/helpers/btc.js
  shared/helpers/eth.js
  shared/helpers/ltc.js
Labels: need review

#1400 wallet: fix remove hash importKeys on close modal
  shared/components/modals/ImportKeys/ImportKeys.js
  shared/pages/Wallet/Wallet.js
Labels: need review

#1401 firebase: fix service worker path
  shared/redux/actions/firebase/index.js
Labels: need review

#1416 helpers: change fee rate speed to fast
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/helpers/btc.js
  shared/helpers/eth.js
  shared/helpers/ethToken.js
  shared/helpers/ltc.js
Labels: need review

#1418 currencyWallet: add getHistory actions
  shared/pages/CurrencyWallet/CurrencyWallet.js
Labels: need review
