Repository swaponline/MultiCurrencyWallet, pull requests merged in 2019-03, with the labels that each got.

#1668 подтверждение отправки запроса на обмен
  shared/components/modal/Modal/Modal.js
  shared/components/modals/Confirm/Confirm.js
  shared/components/modals/Confirm/Confirm.scss
  shared/pages/Home/Orders/Row/Row.js
Labels: buidl

#1682 modals: fix confirm modal styles
  shared/components/modal/ModalConductor/ModalConductor.js
  shared/components/modal/ModalConductor/ModalConductor.scss
  shared/components/modals/Confirm/Confirm.js
  shared/components/modals/Confirm/Confirm.scss
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/Home/Orders/Orders.js
  shared/pages/Home/Orders/Row/Row.js
Labels: need review

#1746 убрать анимацию логотипа прелоадера из за тормозов
  client/index.html
  shared/components/loaders/Loader/Loader.js
Labels: question

#1745 Не верный подсчет курса
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/PartialClosure/PartialClosure.js
Labels: buidl

#1733 правки в модалке визроу #1697
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/components/modals/WithdrawModal/WithdrawModal.scss
  shared/components/notification/Notification/Notification.scss
Labels: question

#1756 header: add opening sign up modal for any page, fix firebase api url,…
  shared/components/Header/Header.js
  shared/components/modals/SignUpModal/SignUpModal.js
  shared/containers/App/App.js
  shared/helpers/firebase/config/firebase-client-config.js
  shared/helpers/firebase/config/firebase.js
  shared/helpers/firebase/index.js
  shared/helpers/index.js
  shared/redux/actions/firebase.js
  shared/redux/actions/index.js
Labels: buidl, need review

#1793 WithdrawModal: fix addressIsCorrect for eth tokens
  shared/components/modals/WithdrawModal/WithdrawModal.js
Labels: need review

#1808 WithdrawModal: add transaction error catching, return LTC to wallet
  config/testnet/api.js
  config/testnet/link.js
  shared/components/modals/ImportKeys/ImportKeys.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/components/modals/WithdrawModal/WithdrawModal.scss
  shared/helpers/constants/DEFAULT_FEE_RATES.js
  shared/helpers/constants/coinsWithDynamicFee.js
  shared/helpers/ltc.js
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/Swap/Swap.js
  shared/pages/Wallet/Row/Row.js
  shared/pages/Wallet/Wallet.js
  shared/redux/actions/btc.js
  shared/redux/actions/ltc.js
Labels: need review
