Repository swaponline/MultiCurrencyWallet, pull requests merged in 2019-02, with the labels that each got.

#1473 client: remove jQuery modal
  client/index.html
Labels: need review

#1495 extension: update version
  chrome-extension/manifest.json
Labels: need review

#1501 analytics: change ga to gtag, remove yandex metrika
  client/index.html
  shared/components/modals/SignUpModal/SignUpModal.js
  shared/pages/Wallet/Row/Row.js
  shared/redux/actions/analytics.js
  shared/redux/actions/firebase/index.js
Labels: need review

#1502 Eсли мы на свап онлайне (не в виджет режиме и не в виджете) то адрес получателя надо убрать за галку "Указать адрес кошелька получения"
  shared/localisation/_default.json
  shared/localisation/en.json
  shared/localisation/ru.json
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/PartialClosure/PartialClosure.scss
  shared/pages/PartialClosure/PureComponents/Advantages.scss
Labels: buidl

#1527 addOffer: fix any amount to actual decimals
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
Labels: need review

#1534 WithdrawModal: add full decimals eth token for sending
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/WithdrawModal/WithdrawModal.js
  shared/helpers/constants/TOKEN_DECIMALS.js
Labels: need review

#1546 PartialClosure: add tag exchange-click-selector for analytics
  shared/pages/PartialClosure/PartialClosure.js
  shared/redux/actions/analytics.js
Labels: need review

#1537 динмический фи в конфирм офер
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
  shared/components/modals/OfferModal/ConfirmOffer/ConfirmOffer.js
  shared/helpers/constants/coinsWithDynamicFee.js
  shared/helpers/constants/index.js
  shared/helpers/constants/minAmountOffer.js
Labels: buidl

#1559 AddOffer: fix isDisabled
  shared/components/modals/OfferModal/AddOffer/AddOffer.js
Labels: need review

#1576 Изменить пути внутри валютного кошелька
  shared/pages/CurrencyWallet/CurrencyWallet.js
Labels: question

#1588 В мобильной версии на странице /exchange не видно что вводишь
  shared/pages/PartialClosure/SelectGroup/SelectGroup.scss
Labels: question

#1624 client: fix global visible gtag
  client/index.html
Labels: need review

#1637 Partial rehabilitation - фикс declime в партиал
  shared/components/Header/User/UserTooltip/UserTooltip.js
  shared/containers/Core/Core.js
  shared/instances/newSwap.js
  shared/pages/Home/Orders/Orders.js
  shared/pages/PartialClosure/PartialClosure.js
  shared/pages/Swap/DeleteSwapAfterEnd.js
  shared/pages/Swap/Swap.js
  shared/redux/actions/core.js
Labels: challenge, epic, help wanted

#1649 actions: fix setAllowanceForToken method
  shared/redux/actions/token.js
Labels: need review

#1661 firebase: add check apple for iframe
  shared/redux/actions/firebase/index.js
Labels: buidl, need review
