Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-04, with the labels that each got.

#4177 Add "mining fee is too high" to faq
  src/front/shared/components/FAQ/FAQ.tsx
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
Labels: needs review

#4176 Wrong size calculation
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/helpers/btc.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
Labels: reviewed

#4186 Add tests: btc send
  babel.config.js
  jest.config.js
  package.json
  src/front/shared/helpers/btc.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
  tests/btc_send.test.ts
Labels: needs review

#4225 Chrome extension: build
  package.json
Labels: needs review

#4218 Refactoring front btc helper
  src/common/helpers/constants/TRANSACTION.ts
  src/common/utils/coin/btc.ts
  src/core/swap.swaps/UTXOBlockchain.ts
  src/front/shared/components/FAQ/FAQ.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/helpers/btc.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
  tests/btc_send.test.ts
Labels: ready

#4231 Farm: delete plugin
  src/front/shared/components/Header/Header.scss
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/Header/Nav/Nav.tsx
  src/front/shared/components/Header/NavMobile/NavMobile.tsx
  src/front/shared/components/Header/config.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/links.ts
  src/front/shared/helpers/web3.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Farm/index.scss
  src/front/shared/pages/Farm/index.tsx
  src/front/shared/pages/Farm/lib/farmfactory.css
  src/front/shared/pages/Farm/lib/farmfactory.js
  src/front/shared/routes/index.tsx
Labels: needs review

#4243 Mainnet clear list of tokens and add wBTC token
  src/bot/config/mainnet/TOKENS.ts
  src/front/config/bsc-mainnet.widget.prod.js
  src/front/config/bsc-mainnet/erc20.js
  src/front/config/bsc-testnet.widget.prod.js
  src/front/config/bsc-testnet/erc20.js
  src/front/config/mainnet.widget.dev.js
  src/front/config/mainnet.widget.prod.js
  src/front/config/mainnet/erc20.js
  src/front/config/testnet.widget.dev.js
  src/front/config/testnet.widget.prod.js
  src/front/config/testnet/erc20.js
  src/front/externalConfigs/mainnet-default.js
  src/front/externalConfigs/mainnet-localhost.js
  src/front/externalConfigs/swaponline.github.io.js
  src/front/externalConfigs/testnet-default.js
  src/front/shared/components/modals/OfferModal/AddOffer/AddOffer.tsx
  src/front/shared/components/modals/OfferModal/AddOffer/Select/Select.scss
  src/front/shared/components/modals/OfferModal/AddOffer/Select/Select.tsx
  src/front/shared/components/ui/CurrencyIcon/images/index.ts
  src/front/shared/components/ui/CurrencyIcon/images/wbtc.svg
  src/front/shared/components/ui/CurrencySelect/Option/Option.scss
  src/front/shared/components/ui/DropDown/index.scss
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/helpers/index.ts
  src/front/shared/helpers/swaps.ts
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/redux/reducers/currencies.ts
Labels: needs review

#4250 Start page: checking for existence
  src/front/shared/containers/App/App.tsx
Labels: needs review

#4303 Marketmaker: show setting by default, translate. Exchange: hide orderbook by default
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/Header/config.tsx
  src/front/shared/components/controls/Button/Button.scss
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/History/SwapsHistory/RowHistory/RowHistory.tsx
  src/front/shared/pages/Marketmaker/FAQ.tsx
  src/front/shared/pages/Marketmaker/MarketmakerPromo.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.scss
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/redux/actions/core.ts
Labels: needs review
