Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-07, with the labels that each got.

#4605 Orderbook: displaying small amounts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/RowFeeds.scss
  src/front/shared/pages/Exchange/Orders/OrderBook/OrderBook.scss
  src/front/shared/pages/Exchange/Orders/OrderBook/OrderBook.tsx
  src/front/shared/pages/Exchange/Orders/OrderBook/Row/Row.scss
  src/front/shared/pages/Exchange/Orders/OrderBook/Row/Row.tsx
Labels: needs review

#4608 Custom tokens: add through Web3
  src/front/shared/components/modals/AddCustomToken/index.tsx
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/CreateWallet/Steps/startPacks.ts
  src/front/shared/redux/actions/erc20LikeAction.ts
  tests/e2e/wallet/walletAddition.test.ts
Labels: needs review

#4609 Cleanup
  src/front/global.d.ts
  src/front/shared/components/Avatar/Avatar.tsx
  src/front/shared/components/Coins/Coins.tsx
  src/front/shared/components/Confirm/Confirm.tsx
  src/front/shared/components/FaqExpandableItem/FaqExpandableItem.tsx
  src/front/shared/components/InvoiceInfoBlock/InvoiceInfoBlock.tsx
  src/front/shared/components/QR/QR.tsx
  src/front/shared/components/Timer/Timer.ts
  src/front/shared/components/controls/Flip/Flip.tsx
  src/front/shared/components/controls/Toggle/Toggle.tsx
  src/front/shared/components/controls/WithdrawButton/WithdrawButton.tsx
  src/front/shared/components/layout/Overlay/Overlay.tsx
  src/front/shared/components/loaders/RequestLoader/RequestLoader.tsx
  src/front/shared/components/modals/DeclineOrdersModal/DeclineOrdersModal.tsx
  src/front/shared/helpers/links.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/History/Filter/FilterLink/FilterLink.tsx
Labels: code health, needs review

#4614 Wallet: allow users to send other assets if some of them have problem with API
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
Labels: bug, needs review

#4629 Update nextcoin backend interfaces
  src/back/nextcoin/nextp.js
  src/back/nextcoin/package.json
Labels: needs review

#4624 E2E tests: add custom tokens
  package.json
  src/front/shared/components/modals/AddCustomToken/index.tsx
  src/front/shared/pages/Wallet/Row/Row.tsx
  tests/e2e/wallet/tokenAddition.test.ts
  tests/e2e/wallet/walletAddition.test.ts
Labels: needs review, testing

#4631 Dependencies: unused packages
  package.json
Labels: needs review

#4618 Unit tests: tests aren't working on Github
  package.json
  src/front/shared/instances/newSwap.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  tests/testWallets.ts
  tests/unit/btcSend.test.ts
  tests/unit/evmSend.test.ts
Labels: needs review

#4641 Tests: better setup
  .github/pull_request_template.md
  .github/workflows/swapTest.yml
  .github/workflows/withdrawTest.yml
  src/front/config/testnet/web3.js
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: needs review, swap test, withdraw tests

#4652 Wallet: interface bugs
  src/front/shared/components/ui/Copy/Copy.tsx
  src/front/shared/components/ui/DropdownMenu/DropdownMenu.scss
  src/front/shared/pages/Wallet/Row/Row.scss
Labels: needs review

#4658 Wallet: interface bugs
  src/front/shared/components/FAQ/FAQ.tsx
  src/front/shared/components/TourWindow/index.tsx
  src/front/shared/components/TourWindow/styles.scss
  src/front/shared/components/ui/DropdownMenu/DropdownMenu.scss
  src/front/shared/components/ui/DropdownMenu/DropdownMenu.tsx
Labels: needs review

#4656 Ropsten to rinkeby
  .github/workflows/deployChromeExtension.yml
  docs/CORE.md
  docs/FAUCETS.md
  src/bot/.env.example
  src/bot/index.ts
  src/core/simple/src/instances/ethereum.ts
  src/core/simple/src/wallet/index.ts
  src/core/tests/setupSwapApp.ts
  src/front/config/mainnet/evmNetworks.js
  src/front/config/mainnet/swapContract.js
  src/front/config/testnet/api.js
  src/front/config/testnet/erc20.js
  src/front/config/testnet/evmNetworkVersions.js
  src/front/config/testnet/evmNetworks.js
  src/front/config/testnet/link.js
  src/front/config/testnet/swapContract.js
  src/front/config/testnet/web3.js
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/metamask.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: needs review, swap test, withdraw tests

#4660 Exchange: add setState from and to addresses when set up get and have values
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: needs review

#4661 Swap History: refactoring swapHistoryRow and add style name for RowFeed
  src/common/messaging/pubsubRoom/createP2PNode.ts
  src/core/simple/src/config/common.ts
  src/core/swap.room/SwapRoom.ts
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/RowFeeds.scss
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/RowFeeds.tsx
  src/front/shared/pages/History/SwapsHistory/RowHistory/RowHistory.tsx
Labels: needs review

#4663 Mnemonic input: interface bugs
  src/front/shared/components/forms/MnemonicInput/MnemonicInput.css
  src/front/shared/components/modals/RestoryMnemonicWallet/RestoryMnemonicWallet.scss
Labels: needs review

#4665 Create Order: fix display exchange rate
  src/front/shared/components/modals/OfferModal/ConfirmOffer/ExchangeRate/ExchangeRate.tsx
Labels: needs review

#4667 Fix transaction info
  src/common/messaging/pubsubRoom/index.ts
  src/front/shared/helpers/index.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Transaction/Transaction.tsx
  src/front/shared/pages/Transaction/TxInfo/index.tsx
  src/front/shared/redux/actions/history.ts
Labels: needs review

#4669 Prepare test wallets for maticTokenToBtc swap and activate start all swap tests
  package.json
  src/common/messaging/pubsubRoom/index.ts
  tests/e2e/prepareToSwap.test.ts
  tests/e2e/send/sendBtc.test.ts
  tests/e2e/swap/btcToEthWbtc.test.ts
  tests/e2e/swap/maticWbtcToBtc.test.ts
  tests/testWallets.ts
Labels: needs review, swap test

#4668 Add warning in mm settings
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Marketmaker/MarketmakerSettings.scss
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
Labels: needs review

#4674 QR code: wrong component render
  src/front/shared/components/QR/QR.scss
  src/front/shared/components/QR/QR.tsx
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.tsx
  src/front/shared/components/modals/ReceiveModal/ReceiveModal.scss
  src/front/shared/components/modals/ReceiveModal/ReceiveModal.tsx
Labels: needs review

#4675 Centering widget tokens
  src/front/shared/components/Coin/Coin.tsx
  src/front/shared/components/ui/CurrencyIcon/CurrencyIcon.tsx
Labels: needs review

#4677 Add translations to multisig modal
  src/front/shared/components/modals/BtcMultisignConfirmTx/BtcMultisignConfirmTx.tsx
  src/front/shared/localisation/en.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
Labels: needs review

#4676 Refactoring
  src/README.md
  src/front/shared/components/modals/BtcMultisignConfirmTx/BtcMultisignConfirmTx.tsx
  src/front/shared/components/modals/InvoiceModal/InvoiceModal.tsx
  src/front/shared/components/modals/WithdrawBtcPin/WithdrawBtcPin.tsx
  src/front/shared/components/modals/WithdrawBtcSms/WithdrawBtcSms.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisig.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/feedback.ts
  src/front/shared/helpers/getTopLocation.ts
  src/front/shared/helpers/index.ts
  src/front/shared/helpers/redirectTo.ts
  src/front/shared/helpers/routing.ts
  src/front/shared/helpers/utils.ts
  src/front/shared/pages/Marketmaker/MarketmakerPromo.tsx
  src/front/shared/pages/Transaction/Transaction.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
  src/front/shared/redux/actions/multisigTx.ts
Labels: needs review

#4678 Add grants in promo
  docs/promo/clr_fund.md
  docs/promo/gitcoin.md
Labels: needs review

#4680 Refactoring
  package.json
  src/front/shared/containers/App/App.tsx
  src/front/shared/containers/App/wdyr.ts
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: needs review

#4681 fix nextd install script
  src/back/nextcoin/README.md
  src/back/nextcoin/nextd-install.sh
  src/back/nextcoin/nextd-start.sh
Labels: needs review

#4682 Multisig history: fix display transactions
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
Labels: needs review

#4683 refactoring sweep code
  src/front/shared/components/layout/DashboardLayout/DashboardLayout.tsx
  src/front/shared/components/layout/DashboardLayout/styles.scss
  src/front/shared/helpers/constants/localStorage.ts
  src/front/shared/helpers/constants/privateKeyNames.ts
  src/front/shared/helpers/getItezUrl.ts
  src/front/shared/helpers/metamask.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/plugins/backupUserData.ts
  src/front/shared/redux/actions/backupManager.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/core.ts
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/redux/actions/ghost.ts
  src/front/shared/redux/actions/next.ts
  src/front/shared/redux/actions/user.ts
  tests/testWallets.ts
Labels: needs review, swap test, withdraw tests
