Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-06, with the labels that each got.

#4475 Swap: refactoring SwapProgressTexts
  src/common/helpers/constants/SWAP_STEPS.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSteps/FirstStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/BtcLikeToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/BtcLikeToEthToken.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/EthToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/EthTokenToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapList.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapProgressTexts/MakerAbToUtxo.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapProgressTexts/MakerUtxoToAb.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapProgressTexts/TakerAbToUtxo.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapProgressTexts/TakerUtxoToAb.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/FirstStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/FourthStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSteps/FourthStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/BtcLikeToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/BtcLikeToEthToken.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/EthToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/EthTokenToBtcLike.tsx
Labels: needs review

#4489 Transactions: fetch tx info with web3. Add a repeat requests in evm tests
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/ThirdStep.tsx
  src/front/shared/redux/actions/ethLikeAction.ts
  tests/unit/evmSend.test.ts
Labels: Refactoring, testing

#4501 History: fix error when componentDidMount
  src/front/shared/pages/History/History.tsx
  tests/e2e/swap/swap.test.ts
Labels: needs review

#4504 SWAP: fix active steps in mobile
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/ABSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapSteps/UTXOSteps/ThirdStep.tsx
Labels: needs review

#4509 Cleanup
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/tools/messages.js
Labels: needs review

#4523 Polygon api. Exchange/MM UI. Breaking errors
  .github/pull_request_template.md
  src/front/config/mainnet/api.js
  src/front/config/mainnet/feeRates.js
  src/front/config/mainnet/link.js
  src/front/config/mainnet/web3.js
  src/front/config/testnet/api.js
  src/front/externalConfigs/mainnet-localhost.js
  src/front/externalConfigs/swaponline.github.io.js
  src/front/shared/components/FAQ/FAQ.tsx
  src/front/shared/helpers/constants/TOKEN_STANDARDS.ts
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Marketmaker/MarketmakerPromo.scss
  src/front/shared/pages/Marketmaker/MarketmakerPromo.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: needs review

#4529 fix allowance when create ethLikeTiken swap and fix test maticWbtcToBtc
  package.json
  src/core/swap.swaps/EthLikeTokenSwap.ts
  src/front/shared/helpers/metamask.ts
  tests/e2e/send/sendBtc.test.ts
  tests/e2e/swap/btcToEthWbtc.test.ts
  tests/e2e/swap/maticWbtcToBtc.test.ts
  tests/testWallets.ts
Labels: needs review

#4477 App: modal window about local storage cleanup
  src/front/client/scss/config/vars/_colors.scss
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/notification/Notification/Notification.scss
  src/front/shared/components/notification/Notification/Notification.tsx
  src/front/shared/components/notification/NotificationConductor/NotificationConductor.scss
  src/front/shared/components/notifications/Message/Message.tsx
  src/front/shared/helpers/feedback.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
Labels: needs review

#4533 Docs: update ADD_BLOCKCHAIN.md. Add data in the missing places
  docs/ADD_BLOCKCHAIN.md
  docs/CORE.md
  src/README.md
  src/common/helpers/constants/MIN_AMOUNT_OFFER.ts
  src/front/shared/components/Footer/Footer.scss
  src/front/shared/components/Footer/Footer.tsx
  src/front/shared/components/SaveKeys/SaveKeys.tsx
  src/front/shared/components/modals/DownloadModal/DownloadModal.tsx
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Currency/Currency.tsx
  src/front/shared/pages/Exchange/SelectGroup/SelectGroup.tsx
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Invoices/CreateInvoice/index.tsx
  src/front/shared/pages/Invoices/Invoice/index.tsx
  src/front/shared/pages/Invoices/InvoicesList/index.tsx
  src/front/shared/plugins/backupUserData.ts
Labels: needs review

#4546 Wallet: fix open withdrawModal
  package.json
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/helpers/metamask.ts
  src/front/shared/helpers/user.ts
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  tests/testWallets.ts
Labels: needs review

#4535 Market maker / Exchange bug fixes
  src/front/client/scss/config/vars/_colors.scss
  src/front/shared/components/ErrorBoundary/index.scss
  src/front/shared/components/ErrorBoundary/index.tsx
  src/front/shared/components/Footer/Footer.scss
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/pages/CreateWallet/Steps/startPacks.ts
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Marketmaker/MarketmakerPromo.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
Labels: needs review

#4550 Exchange: add check at NaN
  src/front/shared/pages/Exchange/AddressSelect/AddressSelect.tsx
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: needs review

#4548 Metamask: check networkId and current address in wallet withdrawal
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  tests/e2e/swap/btcToEthWbtc.test.ts
  tests/testWallets.ts
Labels: UI, needs review

#4554 Exchange: add custom and widget tokens for WP
  docs/CUSTOMIZATION.md
  src/front/externalConfigs/mainnet-default.js
  src/front/externalConfigs/mainnet-localhost.js
  src/front/externalConfigs/swaponline.github.io.js
  src/front/externalConfigs/testnet-default.js
  src/front/shared/components/layout/DashboardLayout/DashboardLayout.tsx
  src/front/shared/components/modals/OfferModal/AddOffer/AddOffer.tsx
  src/front/shared/helpers/constants/TRADE_TICKERS.ts
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/helpers/swaps.ts
  src/front/shared/helpers/user.ts
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/redux/actions/user.ts
  src/front/shared/redux/reducers/currencies.ts
Labels: needs review

#4557 Echange: fix display user addresses in dropdown select
  src/front/shared/helpers/user.ts
  src/front/shared/pages/Exchange/AddressSelect/AddressSelect.tsx
  src/front/shared/redux/actions/core.ts
  src/front/shared/redux/reducers/core.ts
Labels: needs review

#4549 Refactoring. Swap UI. Swap deposit window: different token standards / evm coins
  src/core/swap.app/constants/COINS.ts
  src/front/client/scss/config/vars/_colors.scss
  src/front/shared/components/modal/Modal/Modal.scss
  src/front/shared/components/modal/Modal/Modal.tsx
  src/front/shared/components/modal/ModalBox/ModalBox.scss
  src/front/shared/components/modal/ModalBox/ModalBox.tsx
  src/front/shared/components/modals/Alert/AlertModal.scss
  src/front/shared/components/modals/Alert/AlertModal.tsx
  src/front/shared/components/modals/AlertWindow/index.tsx
  src/front/shared/components/modals/AlertWindow/styles.scss
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.tsx
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.scss
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.tsx
  src/front/shared/components/modals/ReceiveModal/ReceiveModal.tsx
  src/front/shared/components/ui/CloseIcon/CloseIcon.scss
  src/front/shared/components/ui/CloseIcon/CloseIcon.tsx
  src/front/shared/components/ui/Tooltip/Tooltip.tsx
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/Currency/Currency.tsx
  src/front/shared/pages/Exchange/AddressSelect/AddressSelect.tsx
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/History/SwapsHistory/RowHistory/RowHistory.scss
  src/front/shared/pages/History/SwapsHistory/RowHistory/RowHistory.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.scss
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/pages/Marketmaker/SwapRow.scss
  src/front/shared/pages/Marketmaker/SwapRow.tsx
  src/front/shared/pages/Swap/Debug/Debug.scss
  src/front/shared/pages/Swap/Debug/Debug.tsx
  src/front/shared/pages/Swap/Swap.tsx
  src/front/shared/pages/Swap/Timer/Timer.scss
  src/front/shared/pages/Swap/Timer/Timer.tsx
  src/front/shared/pages/Swap/UTXOSwap/DepositWindow/DepositWindow.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapList.scss
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/PleaseDontLeaveWrapper.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/SwapProgress.scss
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/SwapProgress.tsx
  src/front/shared/pages/Wallet/Row/Row.scss
  src/front/shared/redux/actions/core.ts
Labels: needs review

#4562 Statistics
  src/front/client/index.html
  src/front/client/index.tsx
  src/front/shared/helpers/feedback.ts
  src/front/shared/pages/Wallet/Wallet.tsx
Labels: needs review

#4564 Cleanup
  src/front/shared/components/Header/Logo/Logo.tsx
  src/front/shared/helpers/bepToken.ts
  src/front/shared/helpers/cache.ts
  src/front/shared/helpers/getUnixTimeStamp.ts
  src/front/shared/helpers/index.ts
  src/front/shared/helpers/links.ts
  src/front/shared/helpers/lsDataCache.ts
  src/front/shared/helpers/seo.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/About/About.tsx
  src/front/shared/pages/CreateWallet/CreateWallet.scss
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/pages/Exchange/Orders/OrderBook/Row/Row.tsx
  src/front/shared/redux/actions/backupManager.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
  src/front/shared/redux/actions/ghost.ts
  src/front/shared/redux/actions/next.ts
  src/front/shared/redux/actions/usdt.ts
  src/front/shared/redux/actions/user.ts
  src/front/shared/routes/index.tsx
Labels: needs review

#4561 Exchange: add button "Use Correct Network"
  src/common/helpers/constants/AVAILABLE_EVM_NETWORKS.ts
  src/common/helpers/constants/index.ts
  src/common/web3connect/index.ts
  src/front/config/mainnet/evmNetworkVersions.js
  src/front/config/mainnet/evmNetworks.js
  src/front/config/mainnet/index.js
  src/front/config/testnet/evmNetworkVersions.js
  src/front/config/testnet/evmNetworks.js
  src/front/config/testnet/index.js
  src/front/shared/helpers/metamask.ts
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/redux/actions/core.ts
Labels: needs review

#4573 CurrencyWallet: fix filter for use multisig wallet
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
Labels: needs review

#4574 Exchange: move change network button to primary button
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: needs review

#4576 Exchange: fix display wrong blockchain fee
  src/front/shared/helpers/getPairFees.ts
Labels: needs review

#4578 UI improvements
  src/front/shared/components/Coin/Coin.scss
  src/front/shared/components/Coin/Coin.tsx
  src/front/shared/components/ui/CurrencyIcon/CurrencyIcon.scss
  src/front/shared/components/ui/CurrencyIcon/CurrencyIcon.tsx
  src/front/shared/components/ui/CurrencySelect/CurrencySelect.scss
  src/front/shared/components/ui/CurrencySelect/CurrencySelect.tsx
  src/front/shared/components/ui/CurrencySelect/Option/Option.scss
  src/front/shared/pages/CreateWallet/CreateWallet.scss
  src/front/shared/pages/CreateWallet/Steps/FirstStep.tsx
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
Labels: UI, needs review

#4579 Exchange: add check at swap exists
  src/common/helpers/constants/EVM_CONTRACTS_ABI.ts
  src/front/shared/helpers/metamask.ts
  src/front/shared/instances/newSwap.ts
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Exchange/Orders/OrderBook/OrderBook.tsx
  src/front/shared/pages/Exchange/Orders/OrderBook/Row/Row.tsx
  src/front/shared/pages/Exchange/Orders/Orders.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: needs review

#4581 Console: auth errors
  src/front/shared/redux/actions/user.ts
Labels: needs review

#4588 Swaps: remove sign() setTimeout in front and fix gasLimit for all evm transaction
  src/core/swap.swap/AtomicAB2UTXO.ts
  src/core/swap.swaps/EthLikeSwap.ts
  src/core/swap.swaps/EthLikeTokenSwap.ts
  src/front/shared/pages/Swap/UTXOSwap/EthLikeToUTXO.tsx
  src/front/shared/pages/Swap/UTXOSwap/EthTokenToUTXO.tsx
Labels: needs review

#4589 Withdraw Modal: fix input to address error
  src/front/shared/components/modals/InfoInvoice/InfoInvoice.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/History/Row/Row.tsx
Labels: needs review

#4591 Tests: correct test types. Tests for wallet addition
  package.json
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
  src/front/shared/pages/Wallet/Row/Row.tsx
  src/front/shared/redux/actions/btc.ts
  tests/e2e/prepareToSwap.test.ts
  tests/e2e/send/sendBtc.test.ts
  tests/e2e/swap/btcToEthWbtc.test.ts
  tests/e2e/swap/maticWbtcToBtc.test.ts
  tests/e2e/utils.ts
  tests/e2e/wallet/balanceDisplay.test.ts
  tests/e2e/wallet/walletAddition.test.ts
  tests/e2e/withdraw.test.ts
  tests/unit/btcSend.test.ts
  tests/unit/evmSend.test.ts
  tsconfig.json
Labels: needs review

#4590 Create Wallet: create and hide token with baseCurrency
  src/front/config/mainnet/hiddenCoins.js
  src/front/config/testnet/hiddenCoins.js
  src/front/shared/components/modals/AddCustomToken/index.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/helpers/migrations/002_updateHiddenCoinsList.ts
  src/front/shared/helpers/migrations/index.ts
  src/front/shared/helpers/user.ts
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/pages/Exchange/AddressSelect/AddressSelect.tsx
  src/front/shared/pages/Wallet/Row/Row.tsx
  src/front/shared/redux/actions/core.ts
  src/front/shared/redux/reducers/createWallet.ts
Labels: needs review

#4594 Create wallet screen: multiplying custom tokens
  .github/pull_request_template.md
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/pages/CreateWallet/CreateWallet.scss
  src/front/shared/pages/CreateWallet/Steps/FirstStep.tsx
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  tests/e2e/utils.ts
Labels: needs review
