Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-11, with the labels that each got.

#4871 Direct router calls: incorrect allowance check
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/pt.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/QuickSwap/NoSwapsReasons.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/pages/Exchange/QuickSwap/types.ts
Labels: needs review

#4873 Interface: extra settings
  src/front/client/index.html
  src/front/client/variables.css
  src/front/shared/components/Comment/Comment.scss
  src/front/shared/components/controls/Button/Button.scss
  src/front/shared/components/layout/DashboardLayout/DashboardLayout.tsx
  src/front/shared/components/layout/DashboardLayout/styles.scss
  src/front/shared/components/loaders/ContentLoader/ContentLoader.scss
  src/front/shared/components/loaders/ContentLoader/ElementLoading.scss
  src/front/shared/components/modal/Modal/Modal.scss
  src/front/shared/components/modal/ModalConductor/ModalConductor.scss
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.scss
  src/front/shared/components/modals/InfoInvoice/InfoInvoice.scss
  src/front/shared/components/modals/Share/Share.scss
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.scss
  src/front/shared/components/ui/DropdownMenu/DropdownMenu.scss
  src/front/shared/components/ui/Panel/Panel.scss
  src/front/shared/pages/CreateWallet/CreateWallet.scss
  src/front/shared/pages/CreateWallet/Steps/FirstStep.tsx
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.scss
  src/front/shared/pages/Exchange/QuickSwap/index.scss
  src/front/shared/pages/Exchange/index.scss
  src/front/shared/pages/History/History.scss
  src/front/shared/pages/History/SwapsHistory/SwapsHistory.scss
  src/front/shared/pages/Marketmaker/FAQ.scss
  src/front/shared/pages/Marketmaker/MarketmakerSettings.scss
  src/front/shared/pages/Transaction/TxInfo/styles.scss
  src/front/shared/pages/Wallet/Wallet.scss
  webpack/externalConfig.js
Labels: needs review

#4881 Widget: missing title option
  src/front/client/index.html
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/index.ts
  src/front/shared/helpers/seo.ts
Labels: needs review

#4886 Quickswap: ability to leave the network without assets
  src/front/config/mainnet/evmNetworks.js
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/pt.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CreateWallet/Steps/SecondStep.tsx
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/Exchange/QuickSwap/ExchangeForm.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/redux/actions/btcmultisig.ts
Labels: needs review

#4911 Quickswap: aggregator fee
  src/front/config/mainnet/swapContract.js
  src/front/config/testnet/swapContract.js
  src/front/externalConfigs/mainnet-localhost.js
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.tsx
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/pt.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/QuickSwap/UserInfo.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.scss
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/pages/Exchange/QuickSwap/types.ts
Labels: needs review

#4918 Withdraw form: can't withdraw tokens. Cleanup
  src/front/shared/components/BalanceForm/BalanceForm.tsx
  src/front/shared/components/controls/RemoveButton/index.tsx
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.tsx
  src/front/shared/components/modals/InfoInvoice/InfoInvoice.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisig.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisigUser.tsx
  src/front/shared/components/modals/index.ts
  src/front/shared/components/notification/Notification/Notification.tsx
  src/front/shared/components/notifications/Transaction/index.tsx
  src/front/shared/helpers/constants/modals.ts
  src/front/shared/helpers/utils.ts
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/pt.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/QuickSwap/InputForm.tsx
  src/front/shared/pages/Exchange/QuickSwap/UserInfo.tsx
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Wallet/Row/Row.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  tests/e2e/send/sendEvm.test.ts
Labels: needs review, withdraw tests

#4923 fix - tokens with symbol like blockchain (bnb, eth, etc)
  src/common/erc20Like/index.ts
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/helpers/transactions.ts
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
Labels: withdraw tests

#4927 Plugin: disable stats by default
  src/front/client/index.html
  src/front/client/index.tsx
  src/front/shared/helpers/feedback.ts
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
Labels: needs review

#4934 History: displayed invoices even if they disabled
  src/front/client/variables.css
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.scss
  src/front/shared/pages/CreateWallet/CreateWallet.scss
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/History/History.tsx
  src/front/shared/pages/Invoices/InvoicesList/index.tsx
Labels: needs review
