Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-09, with the labels that each got.

#4757 First screen: excess reloading for new users
  src/front/shared/helpers/migrations/002_updateHiddenCoinsList.ts
Labels: needs review

#4756 Quickswap: form bugs
  src/front/shared/components/ErrorBoundary/index.scss
  src/front/shared/components/ErrorBoundary/index.tsx
  src/front/shared/components/controls/Switching/Switching.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/pages/Exchange/AtomicSwap.tsx
  src/front/shared/pages/Exchange/QuickSwap/ExchangeForm.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.scss
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/pages/Exchange/index.tsx
  tests/e2e/prepareToSwap.test.ts
Labels: needs review

#4762 Quickswap: bugs. Feedback: not enough info about problems
  src/common/web3connect/providers/index.ts
  src/front/client/index.html
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.tsx
  src/front/shared/components/modals/LimitOrder/ModalForm.tsx
  src/front/shared/components/modals/LimitOrder/index.tsx
  src/front/shared/helpers/metamask.ts
  src/front/shared/helpers/web3.ts
  src/front/shared/pages/Exchange/Orders/Pair.ts
  src/front/shared/pages/Exchange/QuickSwap/ExchangeForm.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/redux/actions/ghost.ts
  src/front/shared/redux/actions/next.ts
  src/front/shared/redux/actions/oneinch.ts
Labels: needs review

#4775 External wallet: connection
  src/common/web3connect/index.ts
  src/common/web3connect/providers/InjectedProvider.ts
  src/common/web3connect/providers/WalletConnectProvider.ts
  src/common/web3connect/providers/index.ts
  src/front/config/mainnet/evmNetworks.js
  src/front/config/testnet/evmNetworks.js
  src/front/shared/components/Header/WalletConnect/index.tsx
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.scss
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.tsx
  src/front/shared/components/modals/WalletConnectAccount/WalletConnectAccount.tsx
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/helpers/metamask.ts
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/AtomicSwap.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: needs review

#4780 Withdraw: estimate gas for coins txs. Arbitrum: fix withdraw
  src/common/helpers/constants/DEFAULT_CURRENCY_PARAMETERS.ts
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.scss
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/routes/index.tsx
Labels: needs review

#4784 Connected account modal: interface. Quickswap: better currency filter. Cleanup
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.scss
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.tsx
  src/front/shared/components/modals/WalletConnectAccount/WalletConnectAccount.scss
  src/front/shared/components/modals/WalletConnectAccount/WalletConnectAccount.tsx
  src/front/shared/components/ui/CloseIcon/CloseIcon.tsx
  src/front/shared/helpers/metamask.ts
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/redux/actions/ghost.ts
  src/front/shared/redux/actions/next.ts
  src/front/shared/redux/actions/oneinch.ts
  src/front/shared/redux/actions/user.ts
  src/front/shared/redux/reducers/oneinch.ts
  src/front/shared/redux/reducers/pubsubRoom.ts
  tests/e2e/quickSwap/form.test.ts
Labels: reviewed

#4790 Quickswap: feedback for users
  docs/CUSTOMIZATION.md
  src/README.md
  src/front/shared/components/BalanceForm/BalanceForm.tsx
  src/front/shared/components/modals/ConnectWalletModal/ConnectWalletModal.tsx
  src/front/shared/components/modals/InvoiceModal/InvoiceModal.tsx
  src/front/shared/components/modals/LimitOrder/ModalForm.tsx
  src/front/shared/components/modals/WalletConnectAccount/WalletConnectAccount.tsx
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/RowFeeds.tsx
  src/front/shared/pages/Exchange/QuickSwap/NoSwapsReasons.tsx
  src/front/shared/pages/Exchange/QuickSwap/SwapInfo.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.scss
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
Labels: reviewed

#4792 Wallet: restoring
  src/front/shared/components/modals/RestoryMnemonicWallet/RestoryMnemonicWallet.tsx
  src/front/shared/redux/actions/btcmultisig.ts
  src/front/shared/redux/actions/user.ts
Labels: needs review

#4793 Refactoring `getInfoAboutCurrency` for fetch `customExchangeRate`
  src/front/shared/pages/Wallet/Wallet.tsx
  src/front/shared/redux/actions/user.ts
  tests/e2e/utils.ts
Labels: needs review

#4800 BTC-PIN: can't withdraw funds
  src/front/config/testnet/api.js
  src/front/shared/components/modals/WithdrawBtcPin/WithdrawBtcPin.tsx
  src/front/shared/helpers/localStorage.ts
  src/front/shared/helpers/migrations/004_updateBtcPinMnemonicKey.ts
  src/front/shared/helpers/migrations/index.ts
  src/front/shared/redux/actions/user.ts
Labels: needs review

#4802 BTC: withdraw funds
  src/common/utils/coin/btc.ts
  src/front/shared/components/modals/RegisterPINProtected/RegisterPINProtected.tsx
  src/front/shared/components/modals/RestoryMnemonicWallet/RestoryMnemonicWallet.tsx
  src/front/shared/components/modals/SaveMnemonicModal/SaveMnemonicModal.scss
  src/front/shared/helpers/index.ts
  src/front/shared/redux/actions/btc.ts
  src/front/shared/redux/actions/btcmultisig.ts
Labels: withdraw tests

#4798 Quickswap: form improvement. Better transaction check
  src/front/shared/components/forms/Input/Input.scss
  src/front/shared/components/modals/WalletConnectAccount/WalletConnectAccount.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/containers/Transactions/index.tsx
  src/front/shared/helpers/transactions.ts
  src/front/shared/localisation/de.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/QuickSwap/ExchangeForm.tsx
  src/front/shared/pages/Exchange/QuickSwap/NewTokenInstruction.tsx
  src/front/shared/pages/Exchange/QuickSwap/index.tsx
  src/front/shared/pages/Transaction/Transaction.tsx
  src/front/shared/pages/Transaction/TxInfo/index.tsx
  src/front/shared/pages/Transaction/TxInfo/styles.scss
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/redux/reducers/index.ts
  src/front/shared/redux/reducers/transactions.ts
Labels: needs review

#4807 Refactoring
  src/common/utils/mnemonic.ts
  src/front/shared/components/SelectGroup/index.scss
  src/front/shared/components/SelectGroup/index.tsx
  src/front/shared/components/modals/DownloadModal/DownloadModal.scss
  src/front/shared/components/modals/LimitOrder/ModalForm.tsx
  src/front/shared/components/modals/LimitOrder/index.scss
  src/front/shared/components/modals/OfferModal/AddOffer/AddOffer.tsx
  src/front/shared/components/modals/OfferModal/AddOffer/SelectGroup/SelectGroup.tsx
  src/front/shared/pages/Exchange/AtomicSwap.tsx
  src/front/shared/pages/Exchange/QuickSwap/ExchangeForm.tsx
  src/front/shared/pages/Exchange/SelectGroup/SelectGroup.scss
Labels: needs review

#4809 Global / console cleanup
  src/common/utils/apiLooper.ts
  src/front/client/index.html
  src/front/shared/components/BalanceForm/BalanceForm.tsx
  src/front/shared/components/BalanceForm/images/dollar2.svg
  src/front/shared/components/Header/UserTooltip/UserTooltip.tsx
  src/front/shared/components/loaders/ContentLoader/ContentLoader.tsx
  src/front/shared/components/modal/ModalConductor/ModalConductor.tsx
  src/front/shared/components/modals/InfoInvoice/InfoInvoice.scss
  src/front/shared/components/modals/InfoInvoice/InfoInvoice.tsx
  src/front/shared/components/modals/InfoInvoice/images/ready.svg
  src/front/shared/components/modals/WithdrawBtcPin/WithdrawBtcPin.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/notification/NotificationConductor/NotificationConductor.tsx
  src/front/shared/components/ui/DropDown/index.tsx
  src/front/shared/helpers/seo.ts
  src/front/shared/helpers/transactions.ts
  src/front/shared/images/cancelled.svg
  src/front/shared/images/index.ts
  src/front/shared/images/pending.svg
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/Exchange/AtomicSwap.tsx
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/images/accept.svg
  src/front/shared/pages/Exchange/Orders/MyOrders/RowFeeds/images/arrow-right.svg
  src/front/shared/pages/Exchange/images/swapIcon.svg
  src/front/shared/pages/History/Filter/Filter.tsx
  src/front/shared/pages/History/Row/Row.scss
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Wallet/WallerSlider/index.tsx
  src/front/shared/pages/Wallet/images/btc.svg
  src/front/shared/pages/Wallet/images/dollar.svg
  src/front/shared/pages/Wallet/images/pen.svg
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/redux/actions/history.ts
  src/front/shared/redux/actions/user.ts
Labels: needs review

#4814 Languages: ability to set a default language
  src/front/client/colors.css
  src/front/client/index.html
  src/front/shared/components/Footer/SwitchLang/SwitchLang.scss
  src/front/shared/components/Footer/SwitchLang/SwitchLang.tsx
Labels: needs review
