Repository swaponline/MultiCurrencyWallet, pull requests merged in 2021-05, with the labels that each got.

#4321 Navigation: Hide farm link. Exchange: change orderbook button styles
  src/front/shared/components/Header/config.tsx
  src/front/shared/components/controls/Button/Button.scss
  src/front/shared/components/controls/Button/Button.tsx
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: UI, needs review

#4320 Cleanup
  package.json
  src/README.md
  src/common/tests/test-accountFromMnemonic.ts
  src/common/tests/test-getBalance.ts
  src/common/tests/tests.js
  src/common/tests/tests.ts
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/modals/DownloadModal/DownloadModal.tsx
  src/front/shared/components/modals/ReceiveModal/ReceiveModal.tsx
  src/front/shared/helpers/locale.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Swap/UTXOSwap/DepositWindow/DepositWindow.tsx
  src/front/shared/pages/Swap/UTXOSwap/UTXOToEthToken.tsx
  src/front/shared/redux/actions/eth.ts
  src/front/shared/redux/actions/index.ts
  src/front/shared/redux/actions/referral.ts
Labels: Refactoring, code health, needs review

#4333 External package iso-random: delete our hot fix
  package.json
  tempFixes/package.json
Labels: needs review

#4322 Chrome extension: add configs for BSC
  package.json
  src/front/chrome-extension/manifest_.json
  src/front/config/chrome-extension-bsc-mainnet.prod.js
  src/front/config/chrome-extension-bsc-testnet.prod.js
Labels: needs review

#4338 BSC build: enable an admin commission
  src/front/client/index.html
  src/front/shared/helpers/adminFee.ts
Labels: bug, ready

#4347 Withdraw form: close a currency list on the outside click
  src/front/shared/components/OutsideClick/index.tsx
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/components/ui/DropDown/index.tsx
Labels: UI, needs review

#4356 bsc.swap.io: fix redirects
  src/core/swap.app/constants/COINS.ts
  src/front/client/index.html
  src/front/shared/containers/App/App.tsx
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/redux/actions/pairs.ts
Labels: needs review

#4358 Withdraw form: show a double miner fee for AB currency type
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.tsx
  src/front/shared/helpers/links.ts
Labels: ready

#4372 Marketmaker text, Exchange UI
  src/front/shared/helpers/links.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.scss
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Exchange/HowItWorks/HowItWorks.scss
  src/front/shared/pages/Exchange/HowItWorks/HowItWorks.tsx
  src/front/shared/pages/Marketmaker/FAQ.tsx
  src/front/shared/pages/Marketmaker/MarketmakerPromo.scss
  src/front/shared/pages/Marketmaker/MarketmakerPromo.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.scss
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
Labels: ready

#4383 MM - fix history - swap - fix timers for stoped swaps + fix mm extension bg
  package.json
  src/core/swap.swap/Flow.ts
  src/front/chrome-extension/manifest_bsc.json
  src/front/chrome-extension/manifest_eth.json
  src/front/client/index.html
  src/front/shared/components/Avatar/Avatar.tsx
  src/front/shared/containers/App/App.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/pages/Marketmaker/SwapRow.tsx
  src/front/shared/pages/Swap/Swap.tsx
  src/front/shared/pages/Swap/UTXOSwap/EthToUTXO.tsx
  src/front/shared/pages/Swap/UTXOSwap/EthTokenToUTXO.tsx
  src/front/shared/pages/Swap/UTXOSwap/UTXOToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/UTXOToEthToken.tsx
Labels: needs review

#4375 Extension: scripts/workflow renaming. UI fixes. Cleanup
  .github/workflows/chromeExtention.yml
  src/front/config/gravatarUsers.js
  src/front/shared/components/modals/Alert/AlertModal.scss
  src/front/shared/components/modals/Alert/AlertModal.tsx
  src/front/shared/components/modals/SaveMnemonicModal/SaveMnemonicModal.scss
  src/front/shared/components/modals/SaveMnemonicModal/SaveMnemonicModal.tsx
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
Labels: reviewed

#4387 Change e2e tests
  .github/workflows/nodejs.yml
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Exchange/Orders/OrderBook/Row/Row.tsx
  tests/e2e/restoreWallet.test.ts
  tests/e2e/sendBtc.test.ts
  tests/e2e/setupMM.test.ts
  tests/e2e/swap.test.ts
  tests/e2e/utils.ts
Labels: needs review

#4394 BNB price: use this price for the BSC build
  src/front/shared/redux/actions/user.ts
Labels: reviewed

#4399 BSC build: redirect to the exchange page
  src/front/client/index.html
  src/front/shared/containers/App/App.tsx
Labels: reviewed

#4401 fix fetch tx info in tests
  tests/btc_send.test.ts
Labels: needs review

#4416 Enable BNB on swaponline. Wallet: UI fix for tokens standard. History: wrong tx response
  src/front/externalConfigs/swaponline.github.io.js
  src/front/shared/pages/Wallet/Row/Row.scss
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
Labels: UI, bug, needs review

#4393 Swap Flow Redesign
  src/front/config/mainnet/swapConfig.js
  src/front/config/testnet/link.js
  src/front/config/testnet/swapConfig.js
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/Exchange/Exchange.tsx
  src/front/shared/pages/Marketmaker/MarketmakerSettings.tsx
  src/front/shared/pages/Swap/FailControler/FailControler.scss
  src/front/shared/pages/Swap/FailControler/FailControler.tsx
  src/front/shared/pages/Swap/FeeControler/FeeControler.scss
  src/front/shared/pages/Swap/FeeControler/FeeControler.tsx
  src/front/shared/pages/Swap/Swap.scss
  src/front/shared/pages/Swap/Swap.tsx
  src/front/shared/pages/Swap/Timer/Timer.scss
  src/front/shared/pages/Swap/Timer/Timer.tsx
  src/front/shared/pages/Swap/UTXOSwap/DepositWindow/DepositWindow.tsx
  src/front/shared/pages/Swap/UTXOSwap/EthToUTXO.tsx
  src/front/shared/pages/Swap/UTXOSwap/EthTokenToUTXO.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSteps/FirstStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSteps/FourthStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/BtcLikeToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/BtcLikeToEthToken.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/EthToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/ABSwapProgressText/EthTokenToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapList.scss
  src/front/shared/pages/Swap/UTXOSwap/SwapList/SwapList.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSteps/FirstStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSteps/FourthStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSteps/SecondStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSteps/ThirdStep.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/BtcLikeToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/BtcLikeToEthToken.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/EthToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapList/UTXOSwapProgressText/EthTokenToBtcLike.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/SwapProgress.scss
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/SwapProgress.tsx
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/finish.svg
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon0.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon1.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon2.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon3.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon4.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon5.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon6.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon7.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon8.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/icon9.gif
  src/front/shared/pages/Swap/UTXOSwap/SwapProgress/images/index.ts
  src/front/shared/pages/Swap/UTXOSwap/UTXOToEth.tsx
  src/front/shared/pages/Swap/UTXOSwap/UTXOToEthToken.tsx
  src/front/shared/pages/Swap/images/checked.svg
  src/front/shared/pages/Wallet/Row/Row.tsx
Labels: needs review

#4436 Tests: UNIT for sending ETH, BNB; E2E for Wallet, Withdraw, History components
  .github/workflows/testing.yml
  .gitignore
  package.json
  src/common/helpers/ethLikeHelper.ts
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.tsx
  src/front/shared/components/modals/WithdrawBtcMultisig/WithdrawBtcMultisig.tsx
  src/front/shared/components/modals/WithdrawBtcSms/WithdrawBtcSms.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/index.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisig.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisigUser.tsx
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Wallet/Row/Row.scss
  src/front/shared/pages/Wallet/Row/Row.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/ethLikeAction.ts
  src/front/shared/routes/index.tsx
  tests/e2e/history.test.ts
  tests/e2e/index.js
  tests/e2e/readme.md
  tests/e2e/swap.test.ts
  tests/e2e/utils.ts
  tests/e2e/wallet.test.ts
  tests/e2e/withdraw.test.ts
  tests/testWallets.ts
  tests/tests.js
  tests/unit/btcSend.test.ts
  tests/unit/evmSend.test.ts
Labels: needs review

#4444 Wallet: create tokens wallet immediately. Delete Defipulse
  src/common/erc20Like/index.ts
  src/common/helpers/constants/TOKEN_STANDARDS.ts
  src/common/helpers/constants/index.ts
  src/common/helpers/ethLikeHelper.ts
  src/front/config/mainnet/api.js
  src/front/config/mainnet/feeRates.js
  src/front/config/testnet/api.js
  src/front/config/testnet/feeRates.js
  src/front/shared/components/FAQ/FAQ.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/helpers/bnb.ts
  src/front/shared/helpers/constants/TOKEN_DECIMALS.ts
  src/front/shared/helpers/constants/TOKEN_STANDARDS.ts
  src/front/shared/helpers/constants/index.ts
  src/front/shared/helpers/eth.ts
  src/front/shared/helpers/user.ts
  src/front/shared/localisation/es.json
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/user.ts
  src/front/shared/redux/reducers/currencies.ts
  src/front/shared/redux/reducers/user.ts
Labels: ready

#4454 Cleanup
  src/README.md
  src/front/shared/components/Href/TransactionLink.tsx
  src/front/shared/components/modals/SweepToMnemonicKeys/SweepToMnemonicKeys.scss
  src/front/shared/components/modals/SweepToMnemonicKeys/SweepToMnemonicKeys.tsx
  src/front/shared/components/modals/index.ts
  src/front/shared/components/ui/MenuIcon/MenuIcon.scss
  src/front/shared/components/ui/MenuIcon/MenuIcon.tsx
  src/front/shared/components/ui/MenuIcon/images/menu.svg
  src/front/shared/helpers/constants/modals.ts
  src/front/shared/helpers/links.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
Labels: code health, needs review

#4456 Withdraw: extra shadow; Wallet: excess second metamask icon
  src/front/shared/pages/History/History.scss
  src/front/shared/pages/Wallet/Row/Row.tsx
Labels: UI, needs review

#4463 BTC from address is blank and ETH external wallet
  src/front/shared/pages/Exchange/AddressSelect/AddressSelect.tsx
  src/front/shared/pages/Exchange/Exchange.tsx
Labels: needs review

#4452 Correct token addition with different standards. Cleanup
  src/common/coins/getCoinInfo.ts
  src/common/erc20Like/index.ts
  src/common/messaging/pubsubRoom/createP2PNode.ts
  src/core/swap.app/constants/COINS.ts
  src/front/externalConfigs/mainnet-default.js
  src/front/externalConfigs/mainnet-localhost.js
  src/front/externalConfigs/swaponline.github.io.js
  src/front/externalConfigs/testnet-default.js
  src/front/shared/components/Comment/Comment.tsx
  src/front/shared/components/FilterForm/styles.scss
  src/front/shared/components/Header/Header.tsx
  src/front/shared/components/controls/ShareButton/ShareButton.tsx
  src/front/shared/components/layout/DashboardLayout/DashboardLayout.tsx
  src/front/shared/components/modals/AddCustomToken/index.scss
  src/front/shared/components/modals/AddCustomToken/index.tsx
  src/front/shared/components/modals/CurrencyAction/CurrencyAction.tsx
  src/front/shared/components/modals/InfoPay/InfoPay.scss
  src/front/shared/components/modals/InfoPay/InfoPay.tsx
  src/front/shared/components/modals/OfferModal/AddOffer/AddOffer.tsx
  src/front/shared/components/modals/WithdrawModal/WithdrawModal.tsx
  src/front/shared/components/modals/WithdrawModal/components/CurrencyList/index.tsx
  src/front/shared/components/modals/WithdrawModal/components/FeeInfoBlock/FeeRadios/index.tsx
  src/front/shared/components/modals/WithdrawModalMultisig/WithdrawModalMultisig.tsx
  src/front/shared/components/modals/index.ts
  src/front/shared/helpers/adminFee.ts
  src/front/shared/helpers/constants/TOKEN_STANDARDS.ts
  src/front/shared/helpers/constants/TRADE_TICKERS.ts
  src/front/shared/helpers/constants/modals.ts
  src/front/shared/helpers/externalConfig.ts
  src/front/shared/helpers/getWalletLink.ts
  src/front/shared/helpers/links.ts
  src/front/shared/helpers/transactions.ts
  src/front/shared/helpers/user.ts
  src/front/shared/localisation/_default.json
  src/front/shared/localisation/en.json
  src/front/shared/localisation/es.json
  src/front/shared/localisation/nl.json
  src/front/shared/localisation/pl.json
  src/front/shared/localisation/ru.json
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/pages/CreateWallet/Steps/FirstStep.tsx
  src/front/shared/pages/CreateWallet/Steps/StepsWrapper.tsx
  src/front/shared/pages/CurrencyWallet/CurrencyWallet.tsx
  src/front/shared/pages/History/History.tsx
  src/front/shared/pages/History/Row/Row.tsx
  src/front/shared/pages/Transaction/Transaction.tsx
  src/front/shared/pages/Transaction/TxInfo/index.tsx
  src/front/shared/pages/Wallet/Row/Row.tsx
  src/front/shared/pages/Wallet/Wallet.tsx
  src/front/shared/redux/actions/core.ts
  src/front/shared/redux/actions/erc20LikeAction.ts
  src/front/shared/redux/actions/user.ts
  src/front/shared/redux/reducers/currencies.ts
  src/front/shared/redux/reducers/user.ts
Labels: needs review

#4473 Exchange page: exchange rate error
  src/front/shared/redux/actions/user.ts
Labels: needs review

#4468 Tokens: infinite loading when token is first added
  src/front/shared/components/modals/AddCustomToken/index.tsx
  src/front/shared/pages/CreateWallet/CreateWallet.tsx
  src/front/shared/redux/actions/erc20LikeAction.ts
Labels: needs review
